FROM golang:buster

WORKDIR /app
ADD . .
RUN go build -o /usr/local/bin/hello-world

ENV SCOPE=${SCOPE}
ENV TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
ENV BUILDER_READ_RANGE=${BUILDER_READ_RANGE}
ENV BUILDER_SPREADSHEET_ID=${BUILDER_SPREADSHEET_ID}
ENV REQUESTS_SPREADSHEET_ID=${REQUESTS_SPREADSHEET_ID}
ENV REQUESTS_READ_RANGE=${REQUESTS_READ_RANGE}
ENV GOOGLE_CLOUD_CONFIG=${GOOGLE_CLOUD_CONFIG}

EXPOSE 8080
CMD ["/usr/local/bin/hello-world"]