apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-world
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
      - name: hello-world
        image: okteto.dev/go-hello-world:1.0.0
        # env:
        #   - name: SCOPE
        #     value: "https://www.googleapis.com/auth/spreadsheets"
        #   - name: TELEGRAM_TOKEN
        #     value: "6366759286:AAEJhVZuoE-IDFPsKiz1PhBO1QbDyCkzj8w"
        #   - name: BUILDER_SPREADSHEET_ID
        #     value: "1aPGiEbZFJ5rG9xzgUqwTQ0OMqG9uwG7T_cJh_iblDq0"
        #   - name: BUILDER_READ_RANGE
        #     value: "master!1:1000"
        #   - name: REQUESTS_SPREADSHEET_ID
        #     value: "1A4VmMZkBfMxOaIjaRqplWLBzlVAZP6HQNi92cJRIB-c"
        #   - name: REQUESTS_READ_RANGE
        #     value: "master!1:1000"
        #   - name: GOOGLE_CLOUD_CONFIG
        #     value: '{"type":"service_account","project_id":"lan-b2b-bot","private_key_id":"02c22fbf30eaa9b34db014f279aa963950a182f1","private_key":"-----BEGIN PRIVATE KEY-----\nMIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQCWH4iuPMVYMOij\nRQisRhv0Wti9L0UYPmiO7HTrRQ4P1tegl0zd69+iXGy+ceC5bPA5tNpqGFuPeSOI\nc7tnN228384Tr9bJ/ll0EqhNoawkSezKLyuls5C9ycodH59NXh09IcSc+WqtInNJ\n2gK7RYyYpqxsHCOwnjF/RyyT1qOZpVsqF3CdX7wTDrV27paaD332uhqdgzYe1pBz\nxqy6RkORFrdvpPZ6DKVNfqRk58NFJsTWgplTwLaGudx04+66MhBOMdRQ3r/PVsAJ\n4iWeXbLNQbcuxCTiEYGHEN/2LCYLjD/wocoxlfzLv6tsX3nKVxIcZFSo6lU+NX6w\n8u9H3xUvAgMBAAECggEAAsv3mNVBRDN5Uxrz3otZ9XAaO/wJ28Ju8yqxF7oKA9Nk\nrpd8maVFCF6C1GKFIR4mCfOUL7LgeDMgWBLVN5xAE8kdd7iw5weGstWvNt2yuhet\naLQyIbQCjzvs41fgZ77ZPnc+cx/NnJClvO2MBiWonlmMj7aCwhqlsjfcTBMvMmcF\nLqQXUl9Ka3Taa0eyoKWDFpcSBhnWQf2JpN/UCTd8lfY6ls7d9b4MEisK1GwdbeGt\nUzLAYqXfPPx8HdASZo+1FoLU3glWLmKdGp/2l9vkhtKOYS6ZmW/l9za1balduLvD\nHmWMNH5M0iYhEWx9Inr/8vv9CrkmH+Rsf6e6jxvW4QKBgQDL8bMCazs5We/ZO7L2\npL0YSYzeoEkZ0/Aq6NRXyD/6QYrsO/c1/ZrmDzZRUYd1BxhYQn6Omwg4VZt2XBnC\noDlx2hVmS7LPcrtMdoj7D6pXqEV194g2cKTO8FzuqMosph1JSYZf5XyVlc+k///V\nyOo6wsqkwWxYWFenzCy6klifOQKBgQC8cQRvTQU6jMQODOJSh55FgTku09or7bws\nu2wk65Uv0WbxbMvsh65zzH0fDHDGfDImyEdkpQNbZsUY7gEeU2ZPmQC+Pei2k9nR\neWeBF8hTnSsGpTTObL/TkXIGlWaFTIU4WIVNEufW/92gQFKirx7HnRndBFwCqY+I\n0mMN5bHvpwKBgBuok9ZoJIgKonSbnBHHFb4Ne4VVx5QxIgkvulyNU9/ks6qGF2jD\nFBbPSVaN8Aj3BV4y5mcAr4S0V3kd1ICIqkG+idhtu7pWnQApszoZTcjFkWYGQ/re\nG/vUrUXQrlqPzLj7t7WZseO3hYmjDlc4AEwnzsO5V7BDit++2PIUluBBAoGAcL1J\nAvHYg/v9u843hVq/9SNnu71hlNCJuVV0UO5k9hPY++20X1GZrIwV+4Js4kMhmhRO\nqkcTKBbnKpASOTt6RXrrd+YAGWOBeJKiuxgocOXh/PrQCgQEDCbDSm8NxAhQ17IW\nJlN+QyIXTS3Ogqg0yQYTmChoh+s8BYahXooil5cCgYBzJLXeOfrZtEvHnObq1vMU\ncxG7b4NnMGJ3OAWJhj6lJhP5PCe514ZBWXCO6RdPk/PLxRNHZHVqSDCnpnRuaP6n\nkyhgGU7gIpJlZQ1F1q+YhW7Ubp9+/brN0MTrJY321Cp0HO+EZNdlLDDzn2tUyYOB\n2SOEmgzpwVRVmCfIjEcL0g==\n-----END PRIVATE KEY-----\n","client_email":"lan-b2b-bot@lan-b2b-bot.iam.gserviceaccount.com","client_id":"109103876117762689152","auth_uri":"https://accounts.google.com/o/oauth2/auth","token_uri":"https://oauth2.googleapis.com/token","auth_provider_x509_cert_url":"https://www.googleapis.com/oauth2/v1/certs","client_x509_cert_url":"https://www.googleapis.com/robot/v1/metadata/x509/lan-b2b-bot%40lan-b2b-bot.iam.gserviceaccount.com","universe_domain":"googleapis.com"}'

---

apiVersion: v1
kind: Service
metadata:
  name: hello-world
spec:
  type: ClusterIP
  ports:
  - name: "hello-world"
    port: 8080
  selector:
    app: hello-world

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hello-world
  annotations:
    dev.okteto.com/generate-host: hello-world
spec:
  rules:
  - http:
      paths:
      - backend:
          service:
            name: hello-world
            port:
              number: 8080
        path: /
        pathType: ImplementationSpecific